  *** Seats Revision: 942  Build: 2017/09/25 09:48:03                                                            ***
                                                         Quality diagnostics: Seasonality
 
   n   Title                                                      Not-significant               Highly        Unstable     Ureliable        Revisions  Negligible/
                                                        Last Year  Too many changes  Overall    Stationary   (too large   (estimation err.  too large  Spurious
                                                                   in seas. sign                              innov.var.)   too large)
   1   "fatexp_10"                                         No            No            No           No            No            No             No          No 
   2   "fatexp_11"                                         No            No            No           No            No            No             No          No 
   3   "fatexp_13"                                         No            No            No           No            No            No             No          No 
   4   "fatexp_14"                                         No            No            No           No            No            No             No          No 
   5   "fatexp_15"                                         No            No            No           No            No            No             No          No 
   6   "fatexp_16"                                         No            No            No           No            No            No             No          No 
   7   "fatexp_17"                                         No            No            No           No            No            No             No          No 
   8   "fatexp_18"                                         No            No            No           No            No            No             No          No 
   9   "fatexp_19"                                         Yes           No            No           No            No            No             No          No 
  10   "fatexp_20"                                         No            No            No           No            No            No             No          No 
  11   "fatexp_21"                                         No            No            No           No            No            No             No          No 
  12   "fatexp_22"                                         No            No            No           No            No            No             No          No 
  13   "fatexp_23"                                         No            No            No           No            No            No             No          No 
  14   "fatexp_24"                                         No            No            No           No            No            No             No          No 
  15   "fatexp_25"                                         No            No            No           No            No            No             No          No 
  16   "fatexp_26"                                         No            No            No           No            No            No             No          No 
  17   "fatexp_27"                                         No            No            No           No            No            No             No          No 
  18   "fatexp_28"                                         No            No            No           No            No            No             No          No 
  19   "fatexp_29"                                         No            No            No           No            No            No             No          No 
  20   "fatexp_31"                                         No            No            No           No            No            No             No          No 
  21   "fatexp_32"                                         No            No            No           No            No            No             No          No 
  22   "fatexp_33"                                         Yes           No            No           No            No            No             No          No 
  23   "fatexp_c"                                          No            No            No           No            No            No             No          No 
  24   "c_defl"                                            No            No            No           No            No            No             No          No 
  25   "diviz08"                                           No            No            No           No            No            No             No          No 
  26   "divid08"                                           No            No            No           No            No            No             No          No 
  27   "divie08"                                           No            No            No           No            No            No             No          No 
  28   "diviz10"                                           No            No            No           No            No            No             No          No 
  29   "divid10"                                           No            No            No           No            No            No             No          No 
  30   "divie10"                                           No            No            No           No            No            No             No          No 
  31   "diviz11"                                           No            No            No           No            No            No             No          No 
  32   "divid11"                                           No            No            No           No            No            No             No          No 
  33   "divie11"                                           No            No            No           No            No            No             No          No 
  34   "diviz13"                                           No            No            No           No            No            No             No          No 
  35   "divid13"                                           No            No            No           No            No            No             No          No 
  36   "divie13"                                           No            No            No           No            No            No             No          No 
  37   "diviz14"                                           No            No            No           No            No            No             No          No 
  38   "divid14"                                           No            No            No           No            No            No             No          No 
  39   "divie14"                                           No            No            No           No            No            No             No          No 
  40   "diviz15"                                           No            No            No           No            No            No             No          No 
  41   "divid15"                                           No            No            No           No            No            No             No          No 
  42   "divie15"                                           No            No            No           No            No            No             No          No 
  43   "diviz16"                                           No            No            No           No            No            No             No          No 
  44   "divid16"                                           No            No            No           No            No            No             No          No 
  45   "divie16"                                           No            No            No           No            No            No             No          No 
  46   "diviz17"                                           No            No            No           No            No            No             No          No 
  47   "divid17"                                           No            No            No           No            No            No             No          No 
  48   "divie17"                                           No            No            No           No            No            No             No          No 
  49   "diviz18"                                           No            No            No           No            No            No             No          No 
  50   "divid18"                                           No            No            No           No            No            No             No          No 
  51   "divie18"                                           No            No            No           No            No            No             No          No 
  52   "divid19"                                           No            No            No           No            No            No             No          No 
  53   "diviz20"                                           No            No            No           No            No            No             No          No 
  54   "divid20"                                           No            No            No           No            No            No             No          No 
  55   "divie20"                                           No            No            No           No            No            No             No          No 
  56   "diviz21"                                           No            No            No           No            No            No             No          No 
  57   "divid21"                                           No            No            No           No            No            No             No          No 
  58   "divie21"                                           No            No            No           No            No            No             No          No 
  59   "diviz22"                                           No            No            No           No            No            No             No          No 
  60   "divid22"                                           No            No            No           No            No            No             No          No 
  61   "divie22"                                           No            No            No           No            No            No             No          No 
  62   "diviz23"                                           No            No            No           No            No            No             No          No 
  63   "divid23"                                           No            No            No           No            No            No             No          No 
  64   "divie23"                                           No            No            No           No            No            No             No          No 
  65   "diviz24"                                           No            No            No           No            No            No             No          No 
  66   "divid24"                                           No            No            No           No            No            No             No          No 
  67   "divie24"                                           No            No            No           No            No            No             No          No 
  68   "diviz25"                                           No            No            No           No            No            No             No          No 
  69   "divid25"                                           No            No            No           No            No            No             No          No 
  70   "divie25"                                           No            No            No           No            No            No             No          No 
  71   "diviz26"                                           No            No            No           No            No            No             No          No 
  72   "divid26"                                           No            No            No           No            No            No             No          No 
  73   "divie26"                                           No            No            No           No            No            No             No          No 
  74   "diviz27"                                           No            No            No           No            No            No             No          No 
  75   "divid27"                                           No            No            No           No            No            No             No          No 
  76   "divie27"                                           No            No            No           No            No            No             No          No 
  77   "diviz28"                                           No            No            No           No            No            No             No          No 
  78   "divid28"                                           No            No            No           No            No            No             No          No 
  79   "divie28"                                           No            No            No           No            No            No             No          No 
  80   "diviz29"                                           No            No            No           No            No            No             No          No 
  81   "divid29"                                           No            No            No           No            No            No             No          No 
  82   "divie29"                                           No            No            No           No            No            No             No          No 
  83   "diviz30"                                           No            No            No           No            No            No             No          No 
  84   "diviz31"                                           No            No            No           No            No            No             No          No 
  85   "divid31"                                           No            No            No           No            No            No             No          No 
  86   "divie31"                                           No            No            No           No            No            No             No          No 
  87   "diviz32"                                           No            No            No           No            No            No             No          No 
  88   "divid32"                                           No            No            No           No            No            No             No          No 
  89   "divie32"                                           No            No            No           No            No            No             No          No 
  90   "diviz33"                                           Yes           No            No           No            No            No             No          No 
  91   "divid33"                                           No            No            No           No            No            No             No          No 
  92   "migsz_1"                                           No            No            No           No            No            No             No          No 
  93   "nondunaz"                                          No            No            No           No            No            No             No          No 
  94   "nonduest"                                          No            No            No           No            No            No             No          No 
  95   "energnaz"                                          No            No            No           No            No            No             No          No 
  96   "energest"                                          No            No            No           No            No            No             No          No 
  97   "migsz_2"                                           No            No            No           No            No            No             No          No 
  98   "durevnaz"                                          No            No            No           No            No            No             No          No 
  99   "durevest"                                          No            No            No           No            No            No             No          No 
 100   "migsz_3"                                           No            No            No           No            No            No             No          No 
 101   "invesnaz"                                          No            No            No           No            No            No             No          No 
 102   "invesest"                                          No            No            No           No            No            No             No          No 
 103   "migsz_4"                                           No            No            No           No            No            No             No          No 
 104   "internaz"                                          No            No            No           No            No            No             No          No 
 105   "interest"                                          No            No            No           No            No            No             No          No 
