  *** Seats Revision: 942  Build: 2017/09/25 09:48:03                                                            ***
                                                         Quality diagnostics: Seasonality
 
   n   Title                                                      Not-significant               Highly        Unstable     Ureliable        Revisions  Negligible/
                                                        Last Year  Too many changes  Overall    Stationary   (too large   (estimation err.  too large  Spurious
                                                                   in seas. sign                              innov.var.)   too large)
   1   "fatexp_10"                                         No            No            No           No            No            No             No          No 
   2   "fatexp_11"                                         No            No            No           No            No            No             No          No 
   3   "fatexp_13"                                         No            No            No           No            No            No             No          No 
   4   "fatexp_14"                                         No            No            No           No            No            No             No          No 
   5   "fatexp_15"                                         No            No            No           No            No            No             No          No 
   6   "fatexp_16"                                         No            No            No           No            No            No             No          No 
   7   "fatexp_17"                                         No            No            No           No            No            No             No          No 
   8   "fatexp_18"                                         No            No            No           No            No            No             No          No 
   9   "fatexp_19"                                         Yes           No            No           No            No            No             No          No 
  10   "fatexp_20"                                         No            No            No           No            No            No             No          No 
  11   "fatexp_21"                                         No            No            No           No            No            No             No          No 
  12   "fatexp_22"                                         No            No            No           No            No            No             No          No 
  13   "fatexp_23"                                         No            No            No           No            No            No             No          No 
  14   "fatexp_24"                                         No            No            No           No            No            No             No          No 
  15   "fatexp_25"                                         No            No            No           No            No            No             No          No 
  16   "fatexp_26"                                         No            No            No           No            No            No             No          No 
  17   "fatexp_27"                                         No            No            No           No            No            No             No          No 
  18   "fatexp_28"                                         No            No            No           No            No            No             No          No 
  19   "fatexp_29"                                         No            No            No           No            No            No             No          No 
  20   "fatexp_31"                                         No            No            No           No            No            No             No          No 
  21   "fatexp_32"                                         No            No            No           No            No            No             No          No 
  22   "fatexp_33"                                         Yes           No            No           No            No            No             No          No 
  23   "fatexp_c"                                          No            No            No           No            No            No             No          No 
  24   "dfsezdc"                                           No            Yes           No           No            No            No             No          No 
  25   "dfsezec"                                           No            Yes           No           No            No            No             No          No 
  26   "diviz06"                                           No            No            No           No            No            No             No          No 
  27   "divid06"                                           No            No            No           No            No            No             No          No 
  28   "divie06"                                           Yes           No            No           No            No            No             No          No 
  29   "diviz08"                                           No            No            No           No            No            No             No          No 
  30   "divid08"                                           No            No            No           No            No            No             No          No 
  31   "divie08"                                           No            No            No           No            No            No             No          No 
  32   "diviz09"                                           No            No            No           No            No            No             No          No 
  33   "divid09"                                           No            No            No           No            No            No             No          No 
  34   "divie09"                                           No            No            No           No            No            No             No          No 
  35   "diviz10"                                           No            No            No           No            No            No             No          No 
  36   "divid10"                                           No            No            No           No            No            No             No          No 
  37   "divie10"                                           No            No            No           No            No            No             No          No 
  38   "diviz11"                                           No            No            No           No            No            No             No          No 
  39   "divid11"                                           No            No            No           No            No            No             No          No 
  40   "divie11"                                           No            No            No           No            No            No             No          No 
  41   "diviz12"                                           No            No            No           No            No            No             No          No 
  42   "divid12"                                           No            No            No           No            No            No             No          No 
  43   "divie12"                                           Yes           No            No           No            No            No             No          No 
  44   "diviz13"                                           No            No            No           No            No            No             No          No 
  45   "divid13"                                           No            No            No           No            No            No             No          No 
  46   "divie13"                                           No            No            No           No            No            No             No          No 
  47   "diviz14"                                           No            No            No           No            No            No             No          No 
  48   "divid14"                                           No            No            No           No            No            No             No          No 
  49   "divie14"                                           No            No            No           No            No            No             No          No 
  50   "diviz15"                                           No            No            No           No            No            No             No          No 
  51   "divid15"                                           No            No            No           No            No            No             No          No 
  52   "divie15"                                           No            No            No           No            No            No             No          No 
  53   "diviz16"                                           No            No            No           No            No            No             No          No 
  54   "divid16"                                           No            No            No           No            No            No             No          No 
  55   "divie16"                                           No            No            No           No            No            No             No          No 
  56   "diviz17"                                           No            No            No           No            No            No             No          No 
  57   "divid17"                                           No            No            No           No            No            No             No          No 
  58   "divie17"                                           No            No            No           No            No            No             No          No 
  59   "diviz18"                                           No            No            No           No            No            No             No          No 
  60   "divid18"                                           No            No            No           No            No            No             No          No 
  61   "divie18"                                           No            No            No           No            No            No             No          No 
  62   "diviz19"                                           Yes           No            No           No            No            No             No          No 
  63   "divid19"                                           No            No            No           No            No            No             No          No 
  64   "divie19"                                           No            No            No           No            No            No             No          No 
  65   "diviz20"                                           No            No            No           No            No            No             No          No 
  66   "divid20"                                           No            No            No           No            No            No             No          No 
  67   "divie20"                                           No            No            No           No            No            No             No          No 
  68   "diviz21"                                           No            No            No           No            No            No             No          No 
  69   "divid21"                                           No            No            No           No            No            No             No          No 
  70   "divie21"                                           No            No            No           No            No            No             No          No 
  71   "diviz22"                                           No            No            No           No            No            No             No          No 
  72   "divid22"                                           No            No            No           No            No            No             No          No 
  73   "divie22"                                           No            No            No           No            No            No             No          No 
  74   "diviz23"                                           No            No            No           No            No            No             No          No 
  75   "divid23"                                           No            No            No           No            No            No             No          No 
  76   "divie23"                                           No            No            No           No            No            No             No          No 
  77   "diviz24"                                           No            No            No           No            No            No             No          No 
  78   "divid24"                                           No            No            No           No            No            No             No          No 
  79   "divie24"                                           No            No            No           No            No            No             No          No 
  80   "diviz25"                                           No            No            No           No            No            No             No          No 
  81   "divid25"                                           No            No            No           No            No            No             No          No 
  82   "divie25"                                           No            No            No           No            No            No             No          No 
  83   "diviz26"                                           No            No            No           No            No            No             No          No 
  84   "divid26"                                           No            No            No           No            No            No             No          No 
  85   "divie26"                                           No            No            No           No            No            No             No          No 
  86   "diviz27"                                           No            No            No           No            No            No             No          No 
  87   "divid27"                                           No            No            No           No            No            No             No          No 
  88   "divie27"                                           No            No            No           No            No            No             No          No 
  89   "diviz28"                                           No            No            No           No            No            No             No          No 
  90   "divid28"                                           No            No            No           No            No            No             No          No 
  91   "divie28"                                           No            No            No           No            No            No             No          No 
  92   "diviz29"                                           No            No            No           No            No            No             No          No 
  93   "divid29"                                           No            No            No           No            No            No             No          No 
  94   "divie29"                                           No            No            No           No            No            No             No          No 
  95   "diviz30"                                           No            No            No           No            No            No             No          No 
  96   "divid30"                                           No            No            No           No            No            No             No          No 
  97   "divie30"                                           No            No            No           No            No            No             No          No 
  98   "diviz31"                                           No            No            No           No            No            No             No          No 
  99   "divid31"                                           No            No            No           No            No            No             No          No 
 100   "divie31"                                           No            No            No           No            No            No             No          No 
 101   "diviz32"                                           No            No            No           No            No            No             No          No 
 102   "divid32"                                           No            No            No           No            No            No             No          No 
 103   "divie32"                                           No            No            No           No            No            No             No          No 
 104   "diviz33"                                           No            No            No           No            No            No             No          No 
 105   "divid33"                                           No            No            No           No            No            No             No          No 
 106   "divie33"                                           No            No            No           No            No            No             No          No 
 107   "migsz_1"                                           No            No            No           No            No            No             No          No 
 108   "nondunaz"                                          No            No            No           No            No            No             No          No 
 109   "nonduest"                                          No            No            No           No            No            No             No          No 
 110   "migsz15"                                           Yes           No            No           No            No            No             No          No 
 111   "energnaz"                                          No            No            No           No            No            No             No          No 
 112   "energest"                                          No            No            No           No            No            No             No          No 
 113   "migsz_2"                                           No            No            No           No            No            No             No          No 
 114   "durevnaz"                                          No            No            No           No            No            No             No          No 
 115   "durevest"                                          No            No            No           No            No            No             No          No 
 116   "migsz_3"                                           No            No            No           No            No            No             No          No 
 117   "invesnaz"                                          No            No            No           No            No            No             No          No 
 118   "invesest"                                          No            No            No           No            No            No             No          No 
 119   "migsz_4"                                           No            No            No           No            No            No             No          No 
 120   "internaz"                                          No            No            No           No            No            No             No          No 
 121   "interest"                                          No            No            No           No            No            No             No          No 
