VAR LSERVIZIO VARCHAR2(3);
-- VA CAMBIATA LA STRINGA A DESTRA DELLA RIGA SEGUENTE PER DEFINIRE IL SERVIZIO SITIC
EXEC :LSERVIZIO:='TUR';


-- OPZIONI GENERALI
SET LINES 32000
SET TERMOUT OFF ECHO OFF NEWP 0 SPA 0 PAGES 0 FEED OFF TRIMS ON TAB OFF LINESIZE 1000 HEADESEP OFF 
SET COLSEP ";"
SET SERVEROUTPUT ON
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '. ';

-- TABELLA MODELLI APERTI
SPOOL MODELLI.CSV
SELECT  'SERVIZIO','VARIABILE','PROGRESSIVO','CLASS_1','COD_LIVELLO_1','CODICE_1','CLASS_2','COD_LIVELLO_2','CODICE_2','NOME_TS','ANNO_BASE','ANNO_INI','MESE_INI','ANNO_FIN','MESE_FIN','ANNO_SER','MESE_SER','MODELLO','PARAMETRO','VERSIONE' FROM DUAL ;
SELECT * FROM PD_TRAMO.MODELLI
WHERE SERVIZIO=:LSERVIZIO
AND ANNO_FIN IS NULL
;
SPOOL OFF

-- TABELLA RIEPILOGO APERTI
SPOOL RIEPILOGO.CSV
SELECT 'SERVIZIO', 'VARIABILE', 'CLASS_1', 'COD_LIV_1', 'CODICE_1', 'CLASS_2', 'COD_LIV_2', 'CODICE_2', 'FREQUENZA', 'ANNO_BASE','ANNO_INI','MESE_INI','ANNO_FIN','MESE_FIN','APPROCCIO', 'AGGIUSTAMENTO', 'ORDINE_AGGR' FROM DUAL;
SELECT SERVIZIO, VARIABILE, CLASS_1, COD_LIV_1, CODICE_1, CLASS_2, COD_LIV_2, CODICE_2, FREQUENZA, ANNO_BASE, ANNO_INI, MESE_INI, ANNO_FIN, MESE_FIN, APPROCCIO, AGGIUSTAMENTO, ORDINE_AGGR FROM PD_TRAMO.RIEPILOGO
WHERE SERVIZIO=:LSERVIZIO
AND ANNO_FIN IS NULL
;
SPOOL OFF

-- TABELLA INDICI SA
SPOOL INDICISA.CSV
SELECT 'SERVIZIO', 'VARIABILE', 'CATEGORIA_IND', 'TIPO_IND', 'ANNO_BASE', 'ANNO', 'MESE', 'CLASS_1', 'COD_LIV_1', 'CODICE_1', 'CLASS_2', 'COD_LIV_2', 'CODICE_2', 'INDICE', 'DATA_CS', 'I_FLAG'
FROM DUAL;
SELECT V1.SERVIZIO, V1.VARIABILE, V1.CATEGORIA_IND, V1.TIPO_IND, V1.ANNO_BASE, V1.ANNO, V1.MESE, V1.CLASS_1, V1.COD_LIV_1, V1.CODICE_1, V1.CLASS_2, V1.COD_LIV_2, V1.CODICE_2, V1.INDICE, V1.DATA_CS, V1.I_FLAG
FROM
( SELECT SERVIZIO, VARIABILE, CATEGORIA_IND, MAX(TIPO_IND) AS MASSIMO, ANNO_BASE, ANNO, MESE, CLASS_1, COD_LIV_1, CODICE_1, CLASS_2, COD_LIV_2, CODICE_2
   FROM PD_TRAMO.INDICI
   WHERE SERVIZIO=:LSERVIZIO
   AND CATEGORIA_IND='D'
   GROUP BY SERVIZIO, VARIABILE, CATEGORIA_IND, ANNO_BASE, ANNO, MESE, CLASS_1, COD_LIV_1, CODICE_1, CLASS_2, COD_LIV_2, CODICE_2
) V2,
( SELECT SERVIZIO, VARIABILE, CATEGORIA_IND, TIPO_IND, ANNO_BASE, ANNO, MESE, CLASS_1, COD_LIV_1, CODICE_1, CLASS_2, COD_LIV_2, CODICE_2, INDICE, DATA_CS, I_FLAG
   FROM PD_TRAMO.INDICI
   WHERE SERVIZIO=:LSERVIZIO
   AND CATEGORIA_IND='D'
) V1
WHERE 
V1.SERVIZIO = V2.SERVIZIO
AND V1.VARIABILE = V2.VARIABILE
AND V1.ANNO_BASE = V2.ANNO_BASE
AND V1.CLASS_1 = V2.CLASS_1
AND V1.COD_LIV_1 = V2.COD_LIV_1
AND V1.CODICE_1 = V2.CODICE_1
AND V1.CLASS_2 = V2.CLASS_2
AND V1.COD_LIV_2 = V2.COD_LIV_2
AND V1.CODICE_2 = V2.CODICE_2
AND V1.ANNO = V2.ANNO
AND V1.MESE = V2.MESE
AND V1.TIPO_IND = V2.MASSIMO
ORDER BY V1.SERVIZIO, V1.VARIABILE, V1.CATEGORIA_IND, V1.TIPO_IND, V1.ANNO_BASE, V1.CLASS_1, V1.COD_LIV_1, V1.CODICE_1, V1.CLASS_2, V1.COD_LIV_2, V1.CODICE_2, V1.ANNO, V1.MESE
;
SPOOL OFF


-- TABELLA INDICI GREZZI PER I QUALI VENGONO PRODOTTO DATI DESTAGIONALIZZATI
SPOOL INDICI.CSV
SELECT 'SERVIZIO', 'VARIABILE', 'CATEGORIA_IND', 'TIPO_IND', 'ANNO_BASE', 'ANNO', 'MESE', 'CLASS_1', 'COD_LIV_1', 'CODICE_1', 'CLASS_2', 'COD_LIV_2', 'CODICE_2', 'INDICE', 'DATA_CS', 'I_FLAG' FROM DUAL;
SELECT V1.SERVIZIO, V1.VARIABILE, V1.CATEGORIA_IND, V1.TIPO_IND, V1.ANNO_BASE, V1.ANNO, V1.MESE, V1.CLASS_1, V1.COD_LIV_1, V1.CODICE_1, V1.CLASS_2, V1.COD_LIV_2, V1.CODICE_2, V1.INDICE, V1.DATA_CS, V1.I_FLAG
FROM
( SELECT SERVIZIO, VARIABILE, CATEGORIA_IND, MAX(TIPO_IND) AS MASSIMO, ANNO_BASE, ANNO, MESE, CLASS_1, COD_LIV_1, CODICE_1, CLASS_2, COD_LIV_2, CODICE_2
   FROM PD_TRAMO.INDICI
   WHERE SERVIZIO=:LSERVIZIO
   AND CATEGORIA_IND='G'
   GROUP BY SERVIZIO, VARIABILE, CATEGORIA_IND, ANNO_BASE, ANNO, MESE, CLASS_1, COD_LIV_1, CODICE_1, CLASS_2, COD_LIV_2, CODICE_2
) V2
LEFT JOIN
( SELECT SERVIZIO, VARIABILE, CATEGORIA_IND, TIPO_IND, ANNO_BASE, ANNO, MESE, CLASS_1, COD_LIV_1, CODICE_1, CLASS_2, COD_LIV_2, CODICE_2, INDICE, DATA_CS, I_FLAG 
   FROM PD_TRAMO.INDICI
) V1
ON (V1.SERVIZIO = V2.SERVIZIO
AND V1.VARIABILE = V2.VARIABILE
AND V1.CATEGORIA_IND = V2.CATEGORIA_IND
AND V1.TIPO_IND = V2.MASSIMO
AND V1.ANNO_BASE = V2.ANNO_BASE
AND V1.ANNO = V2.ANNO
AND V1.MESE = V2.MESE
AND V1.CLASS_1 = V2.CLASS_1
AND V1.COD_LIV_1 = V2.COD_LIV_1
AND V1.CODICE_1 = V2.CODICE_1
AND V1.CLASS_2 = V2.CLASS_2
AND V1.COD_LIV_2 = V2.COD_LIV_2
AND V1.CODICE_2 = V2.CODICE_2)
LEFT JOIN PD_TRAMO.RIEPILOGO
ON (V1.SERVIZIO = RIEPILOGO.SERVIZIO
AND V1.VARIABILE = RIEPILOGO.VARIABILE
AND V1.ANNO_BASE = RIEPILOGO.ANNO_BASE
AND V1.CLASS_1 = RIEPILOGO.CLASS_1
AND V1.COD_LIV_1 = RIEPILOGO.COD_LIV_1
AND V1.CODICE_1 = RIEPILOGO.CODICE_1
AND V1.CLASS_2 = RIEPILOGO.CLASS_2
AND V1.COD_LIV_2 = RIEPILOGO.COD_LIV_2
AND V1.CODICE_2 = RIEPILOGO.CODICE_2)
WHERE RIEPILOGO.ANNO_FIN IS NULL 
AND RIEPILOGO.AGGIUSTAMENTO>0
ORDER BY V1.SERVIZIO, V1.VARIABILE, V1.ANNO_BASE, V1.CLASS_1, V1.COD_LIV_1, V1.CODICE_1, V1.CLASS_2, V1.COD_LIV_2, V1.CODICE_2, V1.ANNO, V1.MESE
;
SPOOL OFF

EXIT
